/**
 * Encrypts an arbitrary markdown file for client-side decryption.
 *
 * Generalises scripts/encrypt-content.ts (which is hardcoded to the /learn
 * Obsidian note) so any page can ship an encrypted payload.
 *
 * Usage:
 *   ENCRYPTION_PASSWORD="..." npx tsx scripts/encrypt-page.ts <source.md> <output.ts>
 *
 * Example:
 *   ENCRYPTION_PASSWORD="..." npx tsx scripts/encrypt-page.ts \
 *     content-private/glassnudge-system.md \
 *     app/glassnudge/system/encrypted-content.ts
 *
 * The plaintext source MUST NOT be committed. content-private/ is gitignored.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

function preprocessMarkdown(content: string): string {
  // 1. Strip Obsidian frontmatter (first --- block with tags)
  content = content.replace(/^---\n[\s\S]*?\n---\n\n/, '');

  // 2. Convert [[wiki links with aliases]] e.g. [[page|display]] -> display
  content = content.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2');

  // 3. Convert [[wiki links with headings]] e.g. [[page#section]] -> page#section
  content = content.replace(/\[\[([^\]]+#[^\]]+)\]\]/g, (_match, inner: string) => inner);

  // 4. Convert remaining [[wiki links]] -> plain text (remove brackets)
  content = content.replace(/\[\[([^\]]+)\]\]/g, '$1');

  // 5. Fix mermaid edge labels containing grammar-special characters.
  //    Mermaid parses `{`, `}`, `(`, `)`, `[`, `]` in `-->|label|` edges as
  //    syntax, which throws a parse error. Quoting the label makes it plain
  //    text again. Architecture diagrams lean on this heavily — labels like
  //    `-->|POST /v1/entitlements/:id|` are fine, but `-->|sign(payload)|` is not.
  content = content.replace(/```mermaid\n([\s\S]*?)```/g, (block) =>
    block.replace(
      /(-+>|-\.-+>|=+>)\|([^|"][^|]*)\|/g,
      (_edge, arrow: string, label: string) => {
        if (/[{}()[\]}]/.test(label)) {
          return `${arrow}|"${label}"|`;
        }
        return `${arrow}|${label}|`;
      },
    ),
  );

  return content;
}

function toBase64(buffer: ArrayBuffer | Uint8Array): string {
  return Buffer.from(buffer).toString('base64');
}

async function encrypt(
  plaintext: string,
  password: string,
): Promise<{ salt: string; iv: string; ciphertext: string }> {
  const encoder = new TextEncoder();

  // Random salt (16 bytes) and IV (12 bytes for GCM)
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));

  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveKey'],
  );

  const derivedKey = await crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: 600_000, hash: 'SHA-256' },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt'],
  );

  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    derivedKey,
    encoder.encode(plaintext),
  );

  return {
    salt: toBase64(salt),
    iv: toBase64(iv),
    ciphertext: toBase64(encrypted),
  };
}

async function main() {
  const [sourceArg, outputArg] = process.argv.slice(2);
  const password = process.env.ENCRYPTION_PASSWORD;

  if (!sourceArg || !outputArg) {
    console.error('Error: source and output paths are required.');
    console.error(
      'Usage: ENCRYPTION_PASSWORD="..." npx tsx scripts/encrypt-page.ts <source.md> <output.ts>',
    );
    process.exit(1);
  }

  if (!password) {
    console.error('Error: Set ENCRYPTION_PASSWORD environment variable.');
    process.exit(1);
  }

  const sourcePath = path.resolve(process.cwd(), sourceArg);
  const outputPath = path.resolve(process.cwd(), outputArg);

  if (!fs.existsSync(sourcePath)) {
    console.error(`Error: source file not found: ${sourcePath}`);
    process.exit(1);
  }

  console.log(`Reading ${path.relative(process.cwd(), sourcePath)}...`);
  let content = fs.readFileSync(sourcePath, 'utf-8');
  console.log(`  Read ${content.length} characters.`);

  content = preprocessMarkdown(content);
  console.log(`  ${content.length} characters after pre-processing.`);

  // Guard: a diagram that still has an unquoted special-char label will throw
  // at render time, after encryption — surface it here instead.
  const mermaidBlocks = content.match(/```mermaid\n[\s\S]*?```/g) || [];
  console.log(`  ${mermaidBlocks.length} mermaid diagram(s).`);

  console.log('Encrypting with AES-256-GCM (PBKDF2, 600k iterations)...');
  const start = Date.now();
  const { salt, iv, ciphertext } = await encrypt(content, password);
  console.log(`  Done in ${((Date.now() - start) / 1000).toFixed(1)}s.`);

  const outputTs = `// Auto-generated by scripts/encrypt-page.ts — DO NOT EDIT MANUALLY
// Source: ${path.relative(process.cwd(), sourcePath)} (not committed)
// Regenerate: ENCRYPTION_PASSWORD="<password>" npx tsx scripts/encrypt-page.ts ${sourceArg} ${outputArg}

export const salt = '${salt}';
export const iv = '${iv}';
export const ciphertext = '${ciphertext}';
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, outputTs);
  console.log(`\nEncrypted content written to: ${path.relative(process.cwd(), outputPath)}`);
  console.log(`Ciphertext size: ${ciphertext.length} chars (base64)`);
}

main().catch((err) => {
  console.error('Encryption failed:', err);
  process.exit(1);
});
