/**
 * Encrypts the interview prep markdown file for client-side decryption.
 *
 * Usage: ENCRYPTION_PASSWORD="your-password" npx tsx scripts/encrypt-content.ts
 *
 * Output: app/learn/encrypted-content.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const OBSIDIAN_FILE =
  '/Users/arunjacob/Documents/obsidian/Notes/Front-End Interview Questions — Interview Ready Answers.md';
const OUTPUT_FILE = path.resolve(
  import.meta.dirname,
  '../app/learn/encrypted-content.ts',
);

function preprocessMarkdown(content: string): string {
  // 1. Strip Obsidian frontmatter (first --- block with tags)
  const frontmatterRegex = /^---\n[\s\S]*?\n---\n\n/;
  content = content.replace(frontmatterRegex, '');

  // 2. Convert [[wiki links with aliases]] e.g. [[page|display]] -> display
  content = content.replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2');

  // 3. Convert [[wiki links with headings]] e.g. [[page#section]] -> page#section
  content = content.replace(
    /\[\[([^\]]+#[^\]]+)\]\]/g,
    (_match, inner: string) => {
      // Just remove brackets: [[Curated Web concepts#1. What Happens...]] -> plain text
      return inner;
    },
  );

  // 4. Convert remaining [[wiki links]] -> plain text (remove brackets)
  content = content.replace(/\[\[([^\]]+)\]\]/g, '$1');

  // 5. Fix mermaid edge labels containing grammar-special characters.
  //    Mermaid parses `{`, `}`, `(`, `)`, `[`, `]` in `-->|label|` edges as
  //    syntax, which throws a parse error. Quoting the label makes it plain
  //    text again.
  content = content.replace(/```mermaid\n([\s\S]*?)```/g, (block) =>
    block.replace(
      /(-+>|-\.-+>|=+>)\|([^|"][^|]*)\|/g,
      (_edge, arrow: string, label: string) => {
        if (/[{}()[\]}]/.test(label)) {
          return `${arrow}|"${label}"|`;
        }
        return `${arrow}|${label}|`;
      },
    ),
  );

  return content;
}

function toBase64(buffer: ArrayBuffer | Uint8Array): string {
  return Buffer.from(buffer).toString('base64');
}

async function encrypt(
  plaintext: string,
  password: string,
): Promise<{ salt: string; iv: string; ciphertext: string }> {
  const encoder = new TextEncoder();

  // Generate random salt (16 bytes) and IV (12 bytes for GCM)
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));

  // Import password as key material for PBKDF2
  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveKey'],
  );

  // Derive AES-256-GCM key using PBKDF2
  const derivedKey = await crypto.subtle.deriveKey(
    {
      name: 'PBKDF2',
      salt,
      iterations: 600_000,
      hash: 'SHA-256',
    },
    keyMaterial,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt'],
  );

  // Encrypt the plaintext
  const encrypted = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    derivedKey,
    encoder.encode(plaintext),
  );

  return {
    salt: toBase64(salt),
    iv: toBase64(iv),
    ciphertext: toBase64(encrypted),
  };
}

async function main() {
  const password = process.env.ENCRYPTION_PASSWORD;
  if (!password) {
    console.error('Error: Set ENCRYPTION_PASSWORD environment variable.');
    console.error('Usage: ENCRYPTION_PASSWORD="your-password" npx tsx scripts/encrypt-content.ts');
    process.exit(1);
  }

  console.log('Reading markdown file...');
  let content = fs.readFileSync(OBSIDIAN_FILE, 'utf-8');
  console.log(`  Read ${content.length} characters.`);

  console.log('Pre-processing (wiki links, frontmatter)...');
  content = preprocessMarkdown(content);
  console.log(`  ${content.length} characters after pre-processing.`);

  console.log('Encrypting with AES-256-GCM (PBKDF2, 600k iterations)...');
  const start = Date.now();
  const { salt, iv, ciphertext } = await encrypt(content, password);
  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`  Done in ${elapsed}s.`);

  const outputTs = `// Auto-generated by scripts/encrypt-content.ts — DO NOT EDIT MANUALLY
// To regenerate: ENCRYPTION_PASSWORD="<password>" npx tsx scripts/encrypt-content.ts

export const salt = '${salt}';
export const iv = '${iv}';
export const ciphertext = '${ciphertext}';

export interface EncryptedContent {
  salt: string;
  iv: string;
  ciphertext: string;
}
`;

  fs.writeFileSync(OUTPUT_FILE, outputTs);
  console.log(`\nEncrypted content written to: ${OUTPUT_FILE}`);
  console.log(`Ciphertext size: ${ciphertext.length} chars (base64)`);
}

main().catch((err) => {
  console.error('Encryption failed:', err);
  process.exit(1);
});
